name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - website/**
      - .github/**

  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-24.04
    # Add a linting job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Change if needed

      - name: Upload Files to S3
        run: aws s3 sync website/ s3://${{ secrets.AWS_BUCKET }}/ --delete
  invalidate:
    runs-on: ubuntu-24.04
    needs: upload
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Get all changed files and use a space separator in the output
        id: changed-files
        uses: tj-actions/changed-files@v45.0.7
        with:
          separator: " "
          write_output_files: true
          files: |
            website/**

      - name: Verify the contents of the .github/outputs/added_files.txt file # remove later, debug
        if: ${{ hashFiles('.github/outputs/added_files.txt') }}
        run: |
          cat .github/outputs/added_files.txt

      - name: Transform paths (Replace website/ with /)
        if: ${{ hashFiles('.github/outputs/added_files.txt') }}
        run: |
          sed -i  's#website/##g' added_files.txt
          echo "TRANSFORMED_PATHS=$(cat changed_files.txt)" >> $GITHUB_ENV
          echo "$TRANSFORMED_PATHS"

      - name: Invalidate cache on changed files
        if: ${{ hashFiles('.github/outputs/added_files.txt') }}
        uses: chetan/invalidate-cloudfront-action@v2.4
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS_FROM: changed_files.txt
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
