name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - website/**
      - .github/**

  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-24.04
    # Add a linting job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Change if needed

      - name: Upload Files to S3
        run: aws s3 sync website/ s3://${{ secrets.AWS_BUCKET }}/ --delete
  invalidate:
    runs-on: ubuntu-24.04
    needs: upload
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Get all changed files and use a space separator in the output
        id: changed-files
        uses: tj-actions/changed-files@v45.0.7
        with:
          separator: " "
          write_output_files: true
          files: |
            website/**

      - name: Check if all_changed_files.txt is empty or missing
        id: check-file
        run: |
          if [ -s ".github/outputs/all_changed_files.txt" ]; then
            echo "FILE_EMPTY=false" >> $GITHUB_ENV
            ls -la .github/outputs/
          else
            echo "FILE_EMPTY=true" >> $GITHUB_ENV
            ls -la .github/outputs/
          fi

      - name: Debug - Show file contents
        if: env.FILE_EMPTY == 'false'
        run: cat .github/outputs/all_changed_files.txt

      - name: Transform paths (Replace website/ with /)
        if: env.FILE_EMPTY == 'false'
        run: |
          sed -i 's#website/##g' .github/outputs/all_changed_files.txt

      - name: Invalidate CloudFront cache on changed files
        if: env.FILE_EMPTY == 'false'
        uses: chetan/invalidate-cloudfront-action@v2.4
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS_FROM: .github/outputs/all_changed_files.txt
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
