name: Test

on:
  push:
    branches:
      - main
      - fix/changed_files
    paths:
      - website/**
      - .github/**

  pull_request:
    types:
      - closed
    branches:
      - main
      - fix/changed_files

jobs:
  test:
    if: false
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Checkout Code (Full History)
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0 # ✅ Ensure full commit history is available
      - name: log newly committed messages
        env:
          BEFORE_REF: ${{ github.event.before }}
          AFTER_REF: ${{ github.event.after }}
        run: echo "$BEFORE_REF...$AFTER_REF"

      - name: Get changed files in website/
        id: changed-files
        run: |
          echo "Comparing commits: ${{ github.event.before }}  -> ${{ github.event.after }}"
          echo "${{ github.event.before }} "
          git diff --name-only ${{ github.event.before }}  ${{ github.event.after }} | grep '^website/' | sed 's#website/##' > changed_files.txt || true

          if [ -s changed_files.txt ]; then
            echo "File changes detected in website/. Proceeding with invalidation:"
            cat changed_files.txt
            echo "file_empty=false" >> $GITHUB_ENV
          else
            echo "No relevant changes detected. Skipping invalidation."
            echo "file_empty=true" >> $GITHUB_ENV
          fi
